export const classes: {[key: string]: string[]} = {
  "death-knight": ['blood', 'frost', 'unholy'],
  "demon-hunter": ['havoc', 'vengeance'],
  "druid": ['balance', 'feral', 'guardian', 'restoration'],
  "evoker": ['devastation', 'preservation'],
  "hunter": ['beast-mastery', 'marksmanship', 'survival'],
  "mage": ['arcane', 'fire', 'frost'],
  "monk": ['brewmaster', 'mistweaver', 'windwalker'],
  "paladin": ['holy', 'protection', 'retribution'],
  "priest": ['discipline', 'holy', 'shadow'],
  "rogue": ['assassination', 'outlaw', 'subtlety'],
  "shaman": ['elemental', 'enhancement', 'restoration'],
  "warlock": ['affliction', 'demonology', 'destruction'],
  "warrior": ['arms', 'fury', 'protection']
}

export const images: {[key: string]: string} = {
  'death-knight_class': 'classicon_deathknight',
  'death-knight_blood': 'spell_deathknight_bloodpresence',
  'death-knight_frost': 'spell_deathknight_frostpresence',
  'death-knight_unholy': 'spell_deathknight_unholypresence',
  'demon-hunter_class': 'classicon_demonhunter',
  'demon-hunter_havoc': 'ability_demonhunter_specdps',
  'demon-hunter_vengeance': 'ability_demonhunter_spectank',
  'druid_class': 'classicon_druid',
  'druid_balance': 'spell_nature_starfall',
  'druid_feral': 'ability_druid_catform',
  'druid_guardian': 'ability_racial_bearform',
  'druid_restoration': 'spell_nature_healingtouch',
  'evoker_class': 'classicon_evoker',
  'evoker_devastation': 'classicon_evoker_devastation',
  'evoker_preservation': 'classicon_evoker_preservation',
  'hunter_class': 'classicon_hunter',
  'hunter_beast-mastery': 'ability_hunter_bestialdiscipline',
  'hunter_marksmanship': 'ability_hunter_focusedaim',
  'hunter_survival': 'ability_hunter_camouflage',
  'mage_class': 'classicon_mage',
  'mage_arcane': 'spell_holy_magicalsentry',
  'mage_fire': 'spell_fire_firebolt02',
  'mage_frost': 'spell_frost_frostbolt02',
  'monk_class': 'classicon_monk',
  'monk_brewmaster': 'monk_stance_drunkenox',
  'monk_mistweaver': 'monk_stance_wiseserpent',
  'monk_windwalker': 'monk_stance_whitetiger',
  'paladin_class': 'classicon_paladin',
  'paladin_holy': 'spell_holy_holybolt',
  'paladin_protection': 'ability_paladin_shieldofthetemplar',
  'paladin_retribution': 'spell_holy_auraoflight',
  'priest_class': 'classicon_priest',
  'priest_discipline': 'spell_holy_powerwordshield',
  'priest_holy': 'spell_holy_guardianspirit',
  'priest_shadow': 'spell_shadow_shadowwordpain',
  'rogue_class': 'classicon_rogue',
  'rogue_assassination': 'ability_rogue_eviscerate',
  'rogue_outlaw': 'ability_backstab',
  'rogue_subtlety': 'ability_stealth',
  'shaman_class': 'classicon_shaman',
  'shaman_elemental': 'spell_nature_lightning',
  'shaman_enhancement': 'spell_nature_lightningshield',
  'shaman_restoration': 'spell_nature_magicimmunity',
  'warlock_class': 'classicon_warlock',
  'warlock_affliction': 'spell_shadow_deathcoil',
  'warlock_demonology': 'spell_shadow_metamorphosis',
  'warlock_destruction': 'spell_shadow_rainoffire',
  'warrior_class': 'classicon_warrior',
  'warrior_arms': 'ability_warrior_savageblow',
  'warrior_fury': 'ability_warrior_innerrage',
  'warrior_protection': 'ability_warrior_defensivestance'
}