export const classes: { [key: string]: string[] } = {
  "death-knight": ['blood', 'frost', 'unholy'],
  "demon-hunter": ['havoc', 'vengeance'],
  "druid": ['balance', 'feral', 'guardian', 'restoration'],
  "evoker": ['devastation', 'preservation', 'augmentation'],
  "hunter": ['beast-mastery', 'marksmanship', 'survival'],
  "mage": ['arcane', 'fire', 'frost'],
  "monk": ['brewmaster', 'mistweaver', 'windwalker'],
  "paladin": ['holy', 'protection', 'retribution'],
  "priest": ['discipline', 'holy', 'shadow'],
  "rogue": ['assassination', 'outlaw', 'subtlety'],
  "shaman": ['elemental', 'enhancement', 'restoration'],
  "warlock": ['affliction', 'demonology', 'destruction'],
  "warrior": ['arms', 'fury', 'protection']
}

export const classImages: { [key: string]: string } = {
  'death-knight_class': 'classicon_deathknight',
  'death-knight_blood': 'spell_deathknight_bloodpresence',
  'death-knight_frost': 'spell_deathknight_frostpresence',
  'death-knight_unholy': 'spell_deathknight_unholypresence',
  'demon-hunter_class': 'classicon_demonhunter',
  'demon-hunter_havoc': 'ability_demonhunter_specdps',
  'demon-hunter_vengeance': 'ability_demonhunter_spectank',
  'druid_class': 'classicon_druid',
  'druid_balance': 'spell_nature_starfall',
  'druid_feral': 'ability_druid_catform',
  'druid_guardian': 'ability_racial_bearform',
  'druid_restoration': 'spell_nature_healingtouch',
  'evoker_class': 'classicon_evoker',
  'evoker_augmentation': 'classicon_evoker_augmentation',
  'evoker_devastation': 'classicon_evoker_devastation',
  'evoker_preservation': 'classicon_evoker_preservation',
  'hunter_class': 'classicon_hunter',
  'hunter_beast-mastery': 'ability_hunter_bestialdiscipline',
  'hunter_marksmanship': 'ability_hunter_focusedaim',
  'hunter_survival': 'ability_hunter_camouflage',
  'mage_class': 'classicon_mage',
  'mage_arcane': 'spell_holy_magicalsentry',
  'mage_fire': 'spell_fire_firebolt02',
  'mage_frost': 'spell_frost_frostbolt02',
  'monk_class': 'classicon_monk',
  'monk_brewmaster': 'spell_monk_brewmaster_spec',
  'monk_mistweaver': 'spell_monk_mistweaver_spec',
  'monk_windwalker': 'spell_monk_windwalker_spec',
  'paladin_class': 'classicon_paladin',
  'paladin_holy': 'spell_holy_holybolt',
  'paladin_protection': 'ability_paladin_shieldofthetemplar',
  'paladin_retribution': 'spell_holy_auraoflight',
  'priest_class': 'classicon_priest',
  'priest_discipline': 'spell_holy_powerwordshield',
  'priest_holy': 'spell_holy_guardianspirit',
  'priest_shadow': 'spell_shadow_shadowwordpain',
  'rogue_class': 'classicon_rogue',
  'rogue_assassination': 'ability_rogue_deadlybrew',
  'rogue_outlaw': 'ability_rogue_waylay',
  'rogue_subtlety': 'ability_stealth',
  'shaman_class': 'classicon_shaman',
  'shaman_elemental': 'spell_nature_lightning',
  'shaman_enhancement': 'spell_shaman_improvedstormstrike',
  'shaman_restoration': 'spell_nature_magicimmunity',
  'warlock_class': 'classicon_warlock',
  'warlock_affliction': 'spell_shadow_deathcoil',
  'warlock_demonology': 'spell_shadow_metamorphosis',
  'warlock_destruction': 'spell_shadow_rainoffire',
  'warrior_class': 'classicon_warrior',
  'warrior_arms': 'ability_warrior_savageblow',
  'warrior_fury': 'ability_warrior_innerrage',
  'warrior_protection': 'ability_warrior_defensivestance'
}

export const colors: { [key: string]: string } = {
  "death-knight_blood": "#231616",
  "death-knight_frost": "#121b2a",
  "death-knight_unholy": "#1a1a16",
  "demon-hunter_havoc": "#0e1707",
  "demon-hunter_vengeance": "#200f40",
  "druid_balance": "#161634",
  "druid_feral": "#221420",
  "druid_guardian": "#221616",
  "druid_restoration": "#161d12",
  "evoker_augmentation": "#141316",
  "evoker_devastation": "#1c0e11",
  "evoker_preservation": "#07140d",
  "hunter_beast-mastery": "#131b2d",
  "hunter_marksmanship": "#181c12",
  "hunter_survival": "#1e1816",
  "mage_arcane": "#1a132f",
  "mage_fire": "#1b0e09",
  "mage_frost": "#01162f",
  "monk_brewmaster": "#131b04",
  "monk_mistweaver": "#0b2221",
  "monk_windwalker": "#23212b",
  "paladin_holy": "#201810",
  "paladin_protection": "#21150b",
  "paladin_retribution": "#1f1612",
  "priest_discipline": "#111d27",
  "priest_holy": "#1e1a0e",
  "priest_shadow": "#181828",
  "rogue_assassination": "#231616",
  "rogue_outlaw": "#151c1c",
  "rogue_subtlety": "#181922",
  "shaman_elemental": "#081a28",
  "shaman_enhancement": "#11112c",
  "shaman_restoration": "#08122a",
  "warlock_affliction": "#050c45",
  "warlock_demonology": "#270e0b",
  "warlock_destruction": "#29170b",
  "warrior_arms": "#071a1f",
  "warrior_fury": "#13110f",
  "warrior_protection": "#2a1b09"
}

export const specIDs: { [key: string]: number } = {
  'death-knight_blood': 250,
  'death-knight_frost': 251,
  'death-knight_unholy': 252,
  'demon-hunter_havoc': 577,
  'demon-hunter_vengeance': 581,
  'druid_balance': 102,
  'druid_feral': 103,
  'druid_guardian': 104,
  'druid_restoration': 105,
  'evoker_devastation': 1467,
  'evoker_preservation': 1468,
  'evoker_augmentation': 1473,
  'hunter_beast-mastery': 253,
  'hunter_marksmanship': 254,
  'hunter_survival': 255,
  'mage_arcane': 62,
  'mage_fire': 63,
  'mage_frost': 64,
  'monk_brewmaster': 268,
  'monk_mistweaver': 270,
  'monk_windwalker': 269,
  'paladin_holy': 65,
  'paladin_protection': 66,
  'paladin_retribution': 70,
  'priest_discipline': 256,
  'priest_holy': 257,
  'priest_shadow': 258,
  'rogue_assassination': 259,
  'rogue_outlaw': 260,
  'rogue_subtlety': 261,
  'shaman_elemental': 262,
  'shaman_enhancement': 263,
  'shaman_restoration': 264,
  'warlock_affliction': 265,
  'warlock_demonology': 266,
  'warlock_destruction': 267,
  'warrior_arms': 71,
  'warrior_fury': 72,
  'warrior_protection': 73
}